config/routes.rb
Rails.application.routes.draw do

  #Users routes
  get '/signup'       => 'users#new'
  post '/users'       => 'users#create'
  get '/user/:id'     => 'users#show'

  #Sessions routes
  get '/login'        => 'sessions#new'
  post '/login'       => 'sessions#create'
  get '/logout'       => 'sessions#destroy'

  #Posts routes - display list of all posts/comments
  root                   'posts#index'
  get '/newest'       => 'posts#newest'
  get '/newcomments'  => 'posts#newcomments'

  #Posts routes - manipulate posts
  get '/post'         => 'posts#new'
  post '/post'        => 'posts#create'
  delete '/post/:id'  => 'posts#destroy'
  get '/post/:id'     => 'posts#show'

  resources :posts, except: [:destroy] do
    
    member do
      post 'vote'  #/posts/3/vote
    end
    
    collection do
      get 'archives'  #/posts/archives
    end
  
    resources :comments do
      member do
        post 'vote'  
      end
    end
  end

  #Comments routes
  post '/post/:id'    => 'comments#create'
  get  '/reply/:id'   => 'comments#show'
  post '/reply/:id'   => 'comments#reply'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :replies, class_name: "Comment",
                      foreign_key: "this_id",
                      as: :commentable
  belongs_to :this, class_name: "Comment"
  has_many :votes, as: :voteable

  def total_votes
    self.up_votes - self.down_votes
  end
  
  def up_votes
    self.votes.where(vote: true).size
  end
  
  def down_votes
    self.votes.where(vote: false).size  
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :link,
            presence: true,
            uniqueness: {
                case_sensitive: false
            }

  belongs_to :user
  has_many  :comments, as: :commentable
  has_many :votes, as: :voteable

  def total_votes
    self.up_votes - self.down_votes
  end
  
  def up_votes
    self.votes.where(vote: true).size
  end
  
  def down_votes
    self.votes.where(vote: false).size  
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :name,
            presence: true,
            uniqueness: {
                case_sensitive: false
            }
  validates_presence_of :password, on: :create

  has_secure_password
  has_many :posts
  has_many :comments, as: :commentable
  has_many :votes

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_authenticated?
    unless current_user
      flash[:danger] = "Credentials invalid"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find params[:id]
  end

  #For creating comment on post
  def create
    @post = Post.find params[:id]
    @comment = @post.comments.create comment_params
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to "/post/" + params[:id]
    else
      flash[:danger] = "No success"
      redirect_to "/"
    end
  end

  #For creating comment on another comment
  def reply
    @comment = Comment.find params[:id]
    @new_comment = @comment.replies.create reply_params
    @new_comment.commentable_id = @comment.id
    @new_comment.user_id = current_user.id

    if @new_comment.save
      flash[:success] = "Success"
      redirect_to "/reply/" + @comment.commentable_id.to_s
    else
      flash[:danger] = "No success"
      redirect_to "/reply/" + params[:id]
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
      if vote.valid?
        flash[:notice] = "Your vote was counted."
      else
        flash[:error] = "You can only vote once."
      end
    redirect_to :back  
  end


  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def reply_params
    params.require(:this).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_authenticated?

  #Display

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def newest
    @posts = Post.all.sort_by{|x| x.created_at}.reverse
    render "posts/index"
  end

  def newcomments
    @comments = Comment.all.sort_by{|x| x.created_at}.reverse
  end


  #Post manipulation

  def show
    @post = Post.find params[:id]
    @comments = @post.comments
  end

  def new
  end

  def create
    @post = @current_user.posts.create(post_params)

    if @post.save
      flash[:success] = "Post created"
      redirect_to root_path
    else
      flash[:danger] = "Error: post not created"
      redirect_to root_path
    end
  end

  def destroy
    result = Post.destroy params[:id]
    respond_to do |format|
      format.html {redirect_to :posts}
      format.json {render json: result}
    end
  end

  def vote
    @post = Post.find(params[:id])
    vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
      if vote.valid?
      else
        flash[:error] = "You can only vote once."
      end
    redirect_to :back
end


  private

  def post_params
    params.require(:post).permit(:title, :link)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate user_params[:email], user_params[:password]

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:danger] = "Invalid credentials"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
    @posts = @user.posts.sort_by{|x| x.created_at}.reverse
    @comments = @user.comments.sort_by{|x| x.created_at}.reverse
      # @user.comments isn't returning anything
  end

  def new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User created"
      redirect_to root_path
    else
      flash[:danger] = "Credentials invalid"
      redirect_to "/signup"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/show.html.erb
<tr>
  <td class="row">
    <div class="small-text subtext"><small><%= @comment.user.name %> <%= @comment.created_at%></small></div>
    <p class="comment-text"><%=@comment.body%></p>
    <br>
    <%= form_for :this do |f| %>
        <%= f.text_area :body %> <br>
        <%= f.submit "Add reply" %>
    <% end %>
  </td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Slacker News</title>
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- could try adding data-no-turbolink="true" to body tag to prevent modals from flashing - hasn't worked yet -->

<%= render "partials/flash" %>

<!-- template table, including orange navbar -->
<table>
  <tbody>
	  <tr>
	    <td id="navbar" bgcolor="#ff6600">
	      <ul id="nav">
	        <li id="brand">S</li>
	        <li><strong><a href="/">Slacker News</a></strong></li>
	        <li><a href="/newest">new</a></li> |
	        <li><a href="/newcomments">comments</a></li> |
	        <li>show</li> |
	        <li>ask</li> |
	        <li>jobs</li> |
	        <li><a href="/post">submit</a></li>
	        <li id="login">
						<% if @current_user %>
							<p>signed in as <span style="font-style: italic"><%= link_to @current_user.name, "/user/" + @current_user.id.to_s %></span> | <%= link_to "logout", "/logout" %></p>
						<% else %>
							<p><%= link_to "login/signup", "/login" %></p>
						<% end %>
	        </li>
	      </ul>
	    </td>
	  </tr>

	  <!-- see posts/index.html.erb for example of what to include in indiviual view yield -->
			<!--  should start with <tr><td class="row"> -->
			<!--  and end with </td></tr> -->
		<%= yield %>

  </tbody>
</table>

</body>
</html>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <h4><%= value %></h4>
    </div>
<% end %>

app/views/partials/_post.html.erb
<%= link_to "/posts/#{p.id}"%>
    <i class='icon-arrow-up'></i>

<%= p.up_votes %>
<br>
<%= p.total_votes %> votes
<br>
<%= link_to vote_post_path(p, vote: false), method: 'post' do %>
    <i class='icon-arrow-down'></i>
<%end %>
<%= post.down_votes %>

app/views/posts/_comment.html.erb
<!--Using a stack system to keep track of level-->
<%queue = Queue.new; if comment.commentable_type == "Post"%>
    <% @level = 0 %>
    <% queue.push @level %>
<% elsif comment.commentable_type == "Comment"%>

    <% @level = 1 %>

    <% if comment.replies.count > 0 %>
        <% @level = 1 + @level %>
        <% comment.replies.count.times do |i| queue.push @level end %>
    <% else %>
        <% @level = @level %>
        <% queue.push @level %>
    <% end %>

<% end %>
<div class="comment" style="margin-left: <%= queue.pop * 50 + 10%>px">
  <%= link_to vote_post_comment_path(comment.id, comment.id, vote: true), method: 'post' do %>
    <i class='icon-arrow-up'>^</i>
  <% end %>
  <br/>
  <%= link_to vote_post_comment_path(comment.id, comment.id, vote: false), method: 'post' do %>
    <i class='icon-arrow-down'>\/</i>
  <%end %>
<div class="small-text subtext"><small><%= comment.total_votes %> points<%= comment.user.name %> <%= comment.created_at %></small></div>
  <p class="comment-text"><%=comment.body%></p>
  <a href="/reply/<%=comment.id %>"><div class="small-text subtext"><small>reply</small></div></a>
  <%= render partial: "comment", collection: comment.replies %>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% i = 1; @posts.each do |p| %>
  <tr>
    <td class="row">
    	<%= link_to vote_post_path(p, vote: true), method: 'post' do %>
    		<i class='icon-arrow-up'>^</i>
    	<% end %>
		<br>
		<%= link_to vote_post_path(p, vote: false), method: 'post' do %>
    		<i class='icon-arrow-down'>\/</i>
		<%end %>
		<%= link_to p.title, "/post/" + p.id.to_s %><small> (<a class="small-text" href="<%= p.link %>"><%= p.link %></a>)</small>
      <div class="small-text subtext">
      	<small><%= p.total_votes %> points by <%= link_to p.user.name, "/user/" + p.user.id.to_s %> created at <%= p.created_at %>
      		<a href="/post/<%= p.id %>"><%= p.comments.count %> comments</a>
       	</small>
        </div>
      <button class="js-delete-btn btn btn-danger" id="<%= p.id %>">Delete</button>
    </td>
  </tr>
<% i = i + 1 end %>

app/views/posts/new.html.erb
<tr>
<td>
<div class="modal show col-md-8 col-md-offset-2" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">New Post</h4>
      </div>
      <div class="modal-body">
<%= form_for :post do |f| %>
         Title: <%= f.text_field :title%><br>
         Link: <%= f.text_field :link%><br>
        <h5>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.</h5>
          <%= f.submit "Submit" %>
      <% end %>
     </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</td>
</tr>

app/views/posts/newcomments.html.erb
<% i = 1; @comments.each do |c| %>
  <tr>
    <td class="row">


<div class="small-text subtext">
  <small>
    by <%= link_to c.user.name, "/user/" + c.user.id.to_s %> on <span style="font-style: italic;"><%= c.commentable_id %></span>, created at <%= c.created_at %>
  </small>
</div>

<%= c.body %>

    </td>
  </tr>
<% i = i + 1 end %>

app/views/posts/show.html.erb
<tr>
  <td class="row">
    <div class="votearrow"></div><%=@post.title%><small> (<a class="small-text" href="<%=@post.link%>"><%=@post.link%></a>)</small>
    <div class="small-text subtext"><small>0 points by <%= link_to @post.user.name, "/user/" + @post.user.id.to_s %> created at <%= @post.created_at %> | <%= @post.comments.count %> comments </small></div>
    <%= form_for :comment do |f| %>
        <%= f.hidden_field @post%>
        <%= f.text_area :body %> <br>
        <%= f.submit "Add comment" %>
    <% end %>
    <br>
    <div id="comments">
      <%= render partial: "comment", collection: @comments %>
    </div>
  </td>
</tr>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>



    <div class="modal show col-md-8 col-md-offset-2" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Sign Up</h4>
          </div>
          <div class="modal-body">
			    <%= form_for :user, url: "/users" do |f| %>
			    username: <%= f.text_field :name %></br>
			    email: <%= f.text_field :email %>
			    password: <%= f.password_field :password %>
			    <%= f.submit "Submit" %>
			<% end %>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/users/show.html.erb
<!-- basic user info -->
<tr>
	<td class="row">
		<h3><%= @user.name %></span></h3>
		<div>user since: <%= @user.created_at.to_s[0...10] %></div>
	</td>
</tr>

<!-- user's posts -->
<tr style="border-top: 2px solid gray;">
	<td class="row">
		<%= @user.name %>'s posts (<%= @posts.count %>)
	</td>
</tr>

<% i = 1; @posts.each do |p| %>
	<tr>
		<td class="row">
			<span class="grey"><%= i %>. </span><div class="votearrow"></div><%= link_to p.title, "/post/" + p.id.to_s %><small> (<a class="small-text" href="<%=p.link%>"><%= p.link %></a>)</small>
			<div class="small-text subtext">
				<small>0 points by <%= link_to p.user.name, "/user/" + p.user.id.to_s %> created at <%= p.created_at %> | <a href="/post/<%= p.id %>"><%= p.comments.count %> comments</a></small>
			</div>
			<button class="js-delete-btn btn btn-danger" id="<%= p.id %>">Delete</button>
		</td>
	</tr>
	<% i = i + 1 %>
<% end %>

<!-- user's commets -->
<tr style="border-top: 2px solid gray;">
	<td class="row">
		<%= @user.name %>'s comments (<%= @comments.count %>)
	</td>
</tr>

<% i = 1; @comments.each do |c| %>
	<tr>
		<td class="row">
			<span class="grey"><%= i %>. </span><div class="votearrow"></div><%= link_to c.title, "/post/" + c.id.to_s %><small> (<a class="small-text" href="<%=p.link%>"><%= c.link %></a>)</small>
			<div class="small-text subtext">
				<small>0 points by <%= link_to p.user.name, "/user/" + c.user.id.to_s %> created at <%= c.created_at %> | <a href="/post/<%= c.id %>"><%= c.comments.count %> comments</a></small>
			</div>
			<button class="js-delete-btn btn btn-danger" id="<%= c.id %>">Delete</button>
		</td>
	</tr>
	<% i = i + 1 %>
<% end %>